version: 2
jobs:
  decentraland-dapps:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: sudo apt-get update && sudo apt install -y libusb-1.0-0 libusb-1.0-0-dev
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm i
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run test

workflows:
  version: 2
  build:
    jobs:
      - decentraland-dapps
